const characterScreen=
{
	load()
	{
		loader.loadMulti(
		[
			["slide","shader"],
			["UI/background.png","image"]
		]);
	},
	draw(d,t)
	{
		//----
	},
	retrieve()
	{
		//BACKGROUND
		characterScreen.backShade=loader.items["UI/background.png"].image.value;
		characterScreen.backPosLoc=game.gl.getAttribLocation(characterScreen.backShade,"a_pos");
		characterScreen.backTexLoc=game.gl.getUniformLocation(characterScreen.backShade,"u_tex");
		characterScreen.backTimeLoc=game.gl.getUniformLocation(characterScreen.backShade,"u_time");
	},
	keyDown(k)
	{
		//----
	},
	keyUp(k)
	{
		//----
	}
};