const characterRenderer=
{
	methods=[],
	dirs=[0,0.25,0,0.5,0.75]
	load()
	{
		loader.loadMulti(
		[
			["character","shader"],
			["sprite/detail/beastfolk/fur/001.png","texture"],
			["sprite/detail/beastfolk/skin/001.png","texture"],
			["sprite/detail/demons/horns/001.png","texture"],
			["sprite/detail/fishfolk/back/00.png","texture"],
			["sprite/detail/fishfolk/back/01.png","texture"],
			["sprite/detail/fishfolk/back/10.png","texture"],
			["sprite/detail/fishfolk/back/11.png","texture"],
			["sprite/detail/nephilim/halo/001.png","texture"],
			["sprite/detail/vampire/fangs/001.png","texture"],
			["sprite/detail/vampire/fangs/002.png","texture"],
			["sprite/ears/.png","texture"],
			["sprite/eyebrows/.png","texture"],
			["sprite/eyes/.png,"texture"],
			["sprite/hair/.png","texture"],
			["sprite/pants/.png","texture"],
			["sprite/shirt/001/.png","texture"],
			["sprite/shoes/","texture"],
			["sprite/00.png","texture"],
			["sprite/01.png","texture"],
			["sprite/10.png","texture"],
			["sprite/11.png","texture"]
		]);
	},
	retrieve()
	{
	},
	draw(data,x,y,dir,frame)
	{
		methods[data.race].draw(data,x,y,dir/4,dirs[frame]);
	}
};